// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN9cbvdVm7NUF6XSrsPXK5v-SAxjBw3aY',
    appId: '1:614716894382:web:39754f3333bf125c15513f',
    messagingSenderId: '614716894382',
    projectId: 'mono-b47e2',
    authDomain: 'mono-b47e2.firebaseapp.com',
    storageBucket: 'mono-b47e2.firebasestorage.app',
    measurementId: 'G-0KHV9J5KBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ34h1YdtaWPdwlwq3fpTE9qYW-XvFjkk',
    appId: '1:614716894382:android:d5352712fe946bd415513f',
    messagingSenderId: '614716894382',
    projectId: 'mono-b47e2',
    storageBucket: 'mono-b47e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJmw7O250Dnpj0-S0wWJO-6JsjBszydc',
    appId: '1:614716894382:ios:fe9702c847098b3915513f',
    messagingSenderId: '614716894382',
    projectId: 'mono-b47e2',
    storageBucket: 'mono-b47e2.firebasestorage.app',
    iosBundleId: 'com.ror.mono',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN9cbvdVm7NUF6XSrsPXK5v-SAxjBw3aY',
    appId: '1:614716894382:web:62aea19746f2636915513f',
    messagingSenderId: '614716894382',
    projectId: 'mono-b47e2',
    authDomain: 'mono-b47e2.firebaseapp.com',
    storageBucket: 'mono-b47e2.firebasestorage.app',
    measurementId: 'G-QPTBWMZTCR',
  );
}
